[build]
target-dir = "target"

[alias]
check-system-duckdb = "--config env.DUCKDB_LIB_DIR='/opt/homebrew/opt/duckdb/lib' --config env.DUCKDB_INCLUDE_DIR='/opt/homebrew/opt/duckdb/include' --config env.DYLD_LIBRARY_PATH='/opt/homebrew/opt/duckdb/lib' check --no-default-features --features duckdb-prebuilt"
test-system-duckdb = "--config env.DUCKDB_LIB_DIR='/opt/homebrew/opt/duckdb/lib' --config env.DUCKDB_INCLUDE_DIR='/opt/homebrew/opt/duckdb/include' --config env.DYLD_LIBRARY_PATH='/opt/homebrew/opt/duckdb/lib' test --no-default-features --features duckdb-prebuilt"
clippy-system-duckdb = "--config env.DUCKDB_LIB_DIR='/opt/homebrew/opt/duckdb/lib' --config env.DUCKDB_INCLUDE_DIR='/opt/homebrew/opt/duckdb/include' --config env.DYLD_LIBRARY_PATH='/opt/homebrew/opt/duckdb/lib' clippy --no-default-features --features duckdb-prebuilt --all-targets -- -D warnings"
check-dev = "--config env.DUCKDB_DOWNLOAD_LIB='1' check --no-default-features --features duckdb-prebuilt"
test-dev = "--config env.DUCKDB_DOWNLOAD_LIB='1' test --no-default-features --features duckdb-prebuilt"
clippy-dev = "--config env.DUCKDB_DOWNLOAD_LIB='1' clippy --no-default-features --features duckdb-prebuilt --all-targets -- -D warnings"
